version: 2
jobs:
  android:
    docker:
      - image: mmatyas/pegasus-qt-android
    environment:
      TOOLS_URL: https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
      QT_TARGET: qt5156_android
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_NDK_ROOT: /opt/android-sdk/ndk/21.4.7075529
    steps:
      - run: git clone https://github.com/mmatyas/pegasus-metadata-editor .
      - run: git checkout -qf ${CIRCLE_SHA1}
      - run: git submodule update --init --recursive
      - run: sed -i "s/android:versionName=\"devel\"/android:versionName=\"$(git describe --always)\"/" src/platform/android/AndroidManifest.xml
      - run: sed -i "s/android:versionCode=\"1\"/android:versionCode=\"$(git rev-list --count HEAD)\"/" src/platform/android/AndroidManifest.xml
      - run: curl -L ${TOOLS_URL}/${QT_TARGET}.tar.xz | tar xJf - -C /opt/
      - run: curl -L ${TOOLS_URL}/openssl-111d_android.tar.xz | tar xJf - -C /opt/
      - run: /opt/${QT_TARGET}/bin/qmake .
      - run: make
      - run: make install INSTALL_ROOT=${PWD}/installdir
      - run: /opt/${QT_TARGET}/bin/androiddeployqt
          --input src/android-pegasus-metaed-deployment-settings.json
          --output ${PWD}/installdir
          --android-platform android-30
          --gradle
      # Deploy
      - run: mkdir dist
      - run: cp
          installdir/build/outputs/apk/debug/installdir-debug.apk
          dist/pegasus-metadata-editor_$(git describe --always)_android.apk
      - run: curl -L -O https://github.com/mmatyas/uploadtool/raw/circleci/upload.sh
      - run: bash ./upload.sh dist/*.apk
  mingw:
    docker:
      - image: mmatyas/pegasus-qt-mingw
    environment:
      TOOLS_URL: https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1
      QT_TARGET: qt5156_win32-mingw-static
    steps:
      - run: git clone https://github.com/mmatyas/pegasus-metadata-editor .
      - run: git checkout -qf ${CIRCLE_SHA1}
      - run: git submodule update --init --recursive
      - run: curl -L ${TOOLS_URL}/${QT_TARGET}.tar.xz | tar xJf - -C /opt/
      - run: curl -L ${TOOLS_URL}/openssl-111d_mingw.tar.xz | tar xJf - -C /opt/
      - run: /opt/${QT_TARGET}_hosttools/bin/qmake .
      - run: make
      - run: make install INSTALL_ROOT=${PWD}/installdir
      - run: i686-w64-mingw32-objdump -p installdir/home/build/project/src/C:/pegasus-metadata-editor/pegasus-metaed.exe | grep 'DLL Name' | sort
      # Deploy
      - run: mkdir -p dist/pegasus-metadata-editor
      - run: cp
          installdir/home/build/project/src/C:/pegasus-metadata-editor/pegasus-metaed.exe
          README.md
          LICENSE.md
          dist/pegasus-metadata-editor/
      - run: cd dist && zip -r
          pegasus-metadata-editor_$(git describe --always)_win-mingw-static.zip
          pegasus-metadata-editor
      - run: curl -L -O https://github.com/mmatyas/uploadtool/raw/circleci/upload.sh
      - run: bash ./upload.sh dist/*.zip
workflows:
  version: 2
  all:
    jobs:
      - android
      - mingw
